### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by pka** [hugoledoux/sst#3]
Hi, just found this Rust application, which I would like to add to https://github.com/pka/awesome-georust
Would you mind clarifying the license?

**Comment by hugoledoux** [comment]
I had forgotten, it's not a super well-organised package (yet).

It's MIT: 85e6f0bc4faf1dd0ee5f174de521cfc5305beb0b

Thanks for adding it to this page!

**Comment by pka** [comment]
Added, thanks a lot!
